### PR TITLE
Extract interfaces

### PR DESCRIPTION
**Pull request by stweedie**
This is work related to issue #411.

Description of changes:
* Most classes that inherit from RecurlyEntity now have an interface. The only ones that don't have a related interface were private or internal to Recurly.
* Besides this, every reference to one of these classes (as a generic type or as a child property) now references the related interface. For example:
```c#
public class InvoiceCollection : RecurlyEntity, IInvoiceCollection
{
    public IInvoice ChargeInvoice { get; private set; }
    public IRecurlyList<IInvoice> CreditInvoices { get; private set; }
}
```
* Because of interface limitations on internal methods, I had to leverage internal extension methods and type checking to access / use the write xml methods. There is an alternative choice to use static methods and pass in the interface as an instance which I had to do in a few places, but some of the properties being written to XML were private.

I also was not able to run the unit tests. For some reason, VS2017 can't find a registered test runner, and installing suggested nuget packages gives SSL issues.

### CODE REVIEW

**Comment by aaron-suarez** [comment]
Upon my initial look over the PR, I think it looks like a lot of breaking changes. I didn't realize when we discussed it before that implicit conversions weren't going to be possible. If merchants specify the type in their integration, like so:
```C#
Account account = Accounts.Get("x");
```
They'll now have to go in and change all of those from the class to the interface or it won't compile. I'm not sure how many people that would break, but it seems like it might cause problems for those that aren't necessarily trying to create a lot of tests around the library.

We'll have to talk internally about whether this amount of breaking changes is going to be something we want to do. My initial thought is to not break V2 so hard because we're going to want to get people onto V3 the next time they have to make a bunch of breaking changes to their integrations.

There's no way to have these interfaces while still preserving the old classes, is there?

**Comment by stweedie** [comment]
I can definitely go back and revert the static calls (for instance, Accounts.Get would return an Account not an IAccount)

Unfortunately, properties on the classes themselves would still have to be interfaces, so there would still be the potential for breaking changes.

As an example,
```C#
public interface IAdjustment : IRecurlyEntity
{
    IShippingAddress ShippingAddress { get; }
}

public class Adjustment : RecurlyEntity, IAdjustment
{
    IShippingAddress ShippingAddress { get; private set; }
}
```

Adjustment.ShippingAddress would still have to be type ```IShippingAddress```.

I'm not sure if this will sufficiently prevent the breaking changes you describe, though

**Comment by aaron-suarez** [comment]
Out of curiosity @stweedie, did you use a tool to make all these conversions or did you manually change everything required for this PR?

**Comment by stweedie** [comment]
I used the 'Extract Interface' tool that is in visual studio, but I did have to manually find all references to the concrete classes and replace them with interfaces.

**Comment by stweedie** [comment]
Alright I have reverted the changes to the static methods. Static methods (such as ```Adjustments.Get()``` will return the concrete type rather than an interface.

Should I go ahead and unwind the IRecurlyList stuff?

**Comment by aaron-suarez** [comment]
I'm glad to hear that the V3 client looks like it will help resolve your mocking/testing issues. We expect to go GA by the end of the year, but you can start using it now as part of the early access program. Check out https://dev.recurly.com/page/recurly-v3-api-early-access and also feel free to send an email to dx@recurly.com to get help getting set up.

That being said, I think I'm going to hand off this conversation to @bhelx who can help guide you further on what he would like to see to get something merged.

**Comment by bhelx** [comment]
Hey @stweedie, @aaron-suarez passed this on to me. I'm gonna take a look at it soon. We are heavily focused on preparing for V3 and I'm very hesitant to make any unnecessary changes to this library as it's been the hardest for us to support. This seems benign but the fact that it's 91 files does worry me. It's a lot of surface area to make sure is correct.

In the mean time, we'd love your feedback on V3. Since we are still in beta, I'm much more open to changing the interface.

**Comment by bhelx** [comment]
@stweedie I thought about this a bit, although it's a good change I think it's just too many files changed and it increases the cognitive load in order to make a change. I'm trying to limit the amount of changes here to necessary changes only so we can focus on the next version of the client. I apologize for closing this late in the process. I should have chimed in earlier that this might be a problem.

Feel free to email us with questions or concerns. Like I said before, would love to get your opinions on V3 which is in a much more fluid position at the moment. Email: dx@recurly.com

**Pull request closed without merging**
