### PR TITLE
Added support for previewing subscription changes

### PR DESCRIPTION
**Pull request by shawnspeak**

### CODE REVIEW

**Comment by bhelx** [comment]
@shawnspeak thanks for the pull request. Could we some more information in the description about what is going on here and how it can be tested?

**Comment by shawnspeak** [comment]
The other recurly libraries have a means of previewing a subscription change (https://docs.recurly.com/api/subscriptions#sub-change-preview). This pull request add's that capability.

A PreviewChange() method was added to the Subscription class that to will POST changes made to the given Subscription instance to the "preview" endpoint. The response is then used to create a new instance of Subscription which contains a Invoice and Adjustments from Recurly.

I'll have to study the current test code more to provide a recommendation for a unit test.

**Comment by bhelx** [comment]
@shawnspeak sorry we fell behind on this. If you do a rebase with the latest changes I can look at getting this in this week.

**Comment by bhelx** [comment]
we are going to pick this up here: https://github.com/recurly/recurly-client-net/pull/116

**Pull request closed without merging**
