### PR TITLE
Adds giftcard redeem endpoint

### PR DESCRIPTION
**Pull request by bhelx**
Addresses #249 

```csharp
// first we create the gift card
var delivery = new Delivery(Delivery.DeliveryMethod.Email);
delivery.GifterName = "Benjamin";
delivery.FirstName = "Sally";
delivery.LastName = "DuMonde";
delivery.PersonalMessage = "Happy birthday!";
delivery.EmailAddress = "sally@example.com";

// the first param can be an account code for the gifter (if it exists) or an Account object for a new account
var giftCard = new GiftCard("benjamin-du-monde", delivery, "test_gift_card", 1000, "USD");

giftCard.Create();

Console.WriteLine(giftCard);
Console.WriteLine(giftCard.RedemptionCode);

// Now let's create sally's account
var recipientAccount = new Account("sally-du-monde");

// you don't need to call create here if the account already exists
recipientAccount.Create();

// Now let's redeem the gift card on sally's account
// this will update the giftCard object
giftCard.Redeem(recipientAccount.AccountCode);

Console.WriteLine(giftCard.RedeemedAt);
```

### CODE REVIEW

**Comment by jjwhite** [comment]
I still see one problem. If a user is redeeming a gift card they are going to be entering a redemption code so I'd need to be able to create a GiftCard object by passing in the redemption code rather than the delivery information since I wouldn't have access to that at the time of redemption.  So, I think we would need something like this: 

```c#
var giftCard = new GiftCard("my-redemption-code");
giftCard.Redeem(recipientAccount.AccountCode);
```

Here is the python example from the documentation that lines up with what I'm trying to do:
```python
account_code = '3345634'
redemption_code = '22FD95994D02B39D'
gift_card = recurly.GiftCard(redemption_code=redemption_code)
gift_card.redeem(account_code)
```

**Comment by bhelx** [comment]
@jjwhite Thanks for pointing that out. I forgot that that GiftCard initializer was internal. I'll change it to public and it should work. Give me a moment to confirm.

**Comment by bhelx** [comment]
Okay, just pushed that change. I confirmed this code works:

```csharp
var giftCard = new GiftCard("20IX974AEJLGUON8");
giftCard.Redeem("sally-du-monde");
Console.WriteLine(giftCard.RedeemedAt);
```

Does that get you what you need?

**Comment by jjwhite** [comment]
That should work.  I'll let you know if I run into any issues.  Thanks!

**Comment by bhelx** [comment]
No problem. I'll do a bump release after it's merged. If you follow this PR you'll get notified on release.

**Pull request merged**
