### PR TITLE
API v2.5 additions

### PR DESCRIPTION
**Pull request by 1TheMuffinMan**

### CODE REVIEW

**Comment by 1TheMuffinMan** [comment]
@bhelx This is still in progress, but opening this PR for visibility for us.

**Comment by bhelx** [comment]
@1TheMuffinMan Do you have the transaction changes yet?

**Comment by 1TheMuffinMan** [comment]
@bhelx I was planning to get you the last changes tonight, but I can get them in sooner if necessary.

**Comment by bhelx** [comment]
@1TheMuffinMan Hey no rush. I was just checking.

**Comment by 1TheMuffinMan** [comment]
@bhelx The rest of the properties for transaction have been added.

**Comment by bhelx** [comment]
Thanks @1TheMuffinMan! Is it okay to remove the WIP now? Everything looks good. Also can we get a rebase there appears to be conflicts.

**Comment by bhelx** [comment]
:+1:

**Pull request merged**
