### PR TITLE
Add conditional to get the invoice number if it exists or get the pre…

### PR DESCRIPTION
**Pull request by joelscrypt**
Addresses Issue: https://github.com/recurly/recurly-client-net/issues/131

…view invoice otherwise

### CODE REVIEW

**Comment by MuffinMan10110** [comment]
@bhelx Any idea what's going on with the build?

**Comment by bhelx** [comment]
@MuffinMan10110 Travis had a networking hiccup I think. Reran the build

**Comment by bhelx** [comment]
Alright, looks good. Will publish 1.3.1 today after I get one more thing in. You should see the bump referenced in the timeline here.

**Comment by bhelx** [comment]
Thanks again @joelscrypt !

**Pull request merged**
